"""Application lifecycle persistence contract."""

from __future__ import annotations

from typing import Any, Protocol


class ApplicationGateway(Protocol):
    def create_application(self, **kwargs: Any) -> dict[str, Any]: ...
    def list_applications(self) -> list[dict[str, Any]]: ...
    def get_application(self, application_id: str) -> dict[str, Any]: ...
    def bind_resume(self, application_id: str, **kwargs: Any) -> dict[str, Any]: ...
    def get_default_resume(self) -> dict[str, Any] | None: ...
    def set_default_resume(self, **kwargs: Any) -> dict[str, Any]: ...
    def submit_application(self, application_id: str, **kwargs: Any) -> dict[str, Any]: ...
    def add_event(self, application_id: str, **kwargs: Any) -> dict[str, Any]: ...
    def correct_event(
        self, application_id: str, event_id: str, **kwargs: Any
    ) -> dict[str, Any]: ...
    def archive_application(self, application_id: str, **kwargs: Any) -> dict[str, Any]: ...
    def propose_event(self, application_id: str, **kwargs: Any) -> dict[str, Any]: ...
    def list_review_tasks(self) -> list[dict[str, Any]]: ...
    def resolve_proposal(self, proposal_id: str, **kwargs: Any) -> dict[str, Any]: ...
