"""Connector persistence contract."""

from __future__ import annotations

from typing import Any, Protocol


class OpenCliError(RuntimeError):
    """Sanitized failure raised by the external OpenCLI adapter."""

    def __init__(self, code: str, message: str) -> None:
        super().__init__(message)
        self.code = code


class ConnectorGateway(Protocol):
    def get_or_create_boss(self) -> dict[str, Any]: ...
    def update_boss(self, **values: Any) -> dict[str, Any]: ...
    def get_or_create_nowcoder(self) -> dict[str, Any]: ...
    def update_nowcoder(self, **values: Any) -> dict[str, Any]: ...
    def list_runs(
        self, *, limit: int = 20, connector_id: str | None = None
    ) -> list[dict[str, Any]]: ...
    def start_run(
        self, *, trigger_type: str, connector_id: str | None = None,
        now: Any | None = None,
    ) -> dict[str, Any]: ...
    def finish_run(self, run_id: str, *, now: Any | None = None, **counts: Any) -> dict[str, Any]: ...
    def fail_run(self, run_id: str, *, error_code: str, now: Any | None = None) -> dict[str, Any]: ...
    def source_event(self, **values: Any) -> tuple[dict[str, Any], bool]: ...
    def complete_event(self, event_id: str, *, job_post_id: str) -> None: ...
    def complete_opportunity_event(self, event_id: str, *, opportunity_id: str) -> None: ...
    def record_event_error(self, event_id: str, *, error_code: str) -> None: ...
    def quarantine_event(self, event_id: str, *, error_code: str) -> None: ...
    def list_quarantine(
        self, *, limit: int = 50, connector_id: str | None = None
    ) -> list[dict[str, Any]]: ...
    def due(self, *, connector_id: str | None = None, now: Any | None = None) -> bool: ...


class OpenCliRunner(Protocol):
    def version(self) -> str: ...
    def boss_status(self, *, profile: str) -> dict[str, Any]: ...
    def boss_login(self, *, profile: str, timeout: int = 300) -> dict[str, Any]: ...
    def boss_search(
        self, *, profile: str, query: str, city: str, limit: int
    ) -> list[dict[str, Any]]: ...
    def boss_detail(self, *, profile: str, security_id: str) -> dict[str, Any]: ...
    def nowcoder_status(self) -> dict[str, Any]: ...
    def nowcoder_login(self, *, timeout: int = 300) -> dict[str, Any]: ...
    def nowcoder_schedule(
        self, *, lookback_days: int, limit: int, query: str = ""
    ) -> list[dict[str, Any]]: ...
