"""Interview persistence contract."""

from typing import Any, Protocol


class InterviewGateway(Protocol):
    def list_interviews(self) -> list[dict[str, Any]]: ...
    def get_interview(self, interview_id: str) -> dict[str, Any]: ...
    def create_interview(self, **values: Any) -> dict[str, Any]: ...
    def reschedule_interview(self, interview_id: str, **values: Any) -> dict[str, Any]: ...
    def cancel_interview(self, interview_id: str, **values: Any) -> dict[str, Any]: ...
    def generate_preparation(self, interview_id: str) -> dict[str, Any]: ...
    def save_record(self, interview_id: str, **values: Any) -> dict[str, Any]: ...
    def list_feedback(self) -> list[dict[str, Any]]: ...
    def resolve_feedback(self, feedback_id: str, **values: Any) -> dict[str, Any]: ...
    def list_improvements(self) -> list[dict[str, Any]]: ...
    def update_improvement(self, improvement_id: str, **values: Any) -> dict[str, Any]: ...
