"""Job-pool persistence contract."""

from __future__ import annotations

from typing import Any, Protocol


class JobGateway(Protocol):
    def import_job(self, **kwargs: Any) -> dict[str, Any]: ...
    def list_jobs(self, *, status: str | None = None) -> list[dict[str, Any]]: ...
    def get_job(self, job_id: str) -> dict[str, Any]: ...
    def analyze_job(self, job_id: str) -> dict[str, Any]: ...
