"""Mail connector persistence contract."""

from typing import Any, Protocol


class MailGateway(Protocol):
    def get(self) -> dict[str, Any]: ...
    def configure(self, **values: Any) -> dict[str, Any]: ...
    def delete_account(self) -> str | None: ...
    def list_messages(self, *, limit: int = 100) -> list[dict[str, Any]]: ...
    def get_message(self, message_id: str) -> dict[str, Any]: ...
    def start_run(self, *, trigger_type: str) -> dict[str, Any]: ...
    def finish_run(self, run_id: str, **values: Any) -> dict[str, Any]: ...
    def fail_run(self, run_id: str, *, error_code: str) -> dict[str, Any]: ...
    def save_message(self, **values: Any) -> tuple[dict[str, Any], bool]: ...
    def save_candidate(self, **values: Any) -> dict[str, Any]: ...
    def attach_candidate(self, message_id: str, **values: Any) -> dict[str, Any]: ...
    def due(self) -> bool: ...
