"""Application-material persistence and workflow contract."""

from __future__ import annotations

from typing import Any, Protocol


class MaterialGateway(Protocol):
    def create_material(self, **kwargs: Any) -> dict[str, Any]: ...
    def list_resumes(self) -> list[dict[str, Any]]: ...
    def list_materials(self) -> list[dict[str, Any]]: ...
    def get_material(self, material_id: str) -> dict[str, Any]: ...
    def fork_resume(self, material_id: str, **kwargs: Any) -> dict[str, Any]: ...
    def diff_versions(self, from_version_id: str, to_version_id: str) -> dict[str, Any]: ...
    def edit_material(self, material_id: str, **kwargs: Any) -> dict[str, Any]: ...
    def review_material(self, material_id: str) -> dict[str, Any]: ...
    def finalize_material(self, material_id: str, **kwargs: Any) -> dict[str, Any]: ...
    def export_path(self, export_id: str, *, preview: bool = False) -> tuple[str, str]: ...
