"""Daily recommendation persistence contract."""

from __future__ import annotations

from typing import Any, Protocol


class RecommendationGateway(Protocol):
    def context(self, job_id: str, *, manual_directions: list[str] | None = None) -> dict[str, Any]: ...
    def existing(self, *, job_id: str, input_hash: str) -> dict[str, Any] | None: ...
    def save(self, **kwargs: Any) -> dict[str, Any] | None: ...
    def save_failure(self, **kwargs: Any) -> None: ...
    def list(self, *, status: str = "active") -> dict[str, Any]: ...
    def get(self, recommendation_id: str) -> dict[str, Any]: ...
    def dismiss(self, recommendation_id: str, *, expected_version: int, reason: str) -> dict[str, Any]: ...
    def mark_applied(self, recommendation_id: str, **kwargs: Any) -> dict[str, Any]: ...
