"""Read contract for unified reviews and AgentRun audits."""

from __future__ import annotations

from typing import Any, Protocol


class RuntimeGateway(Protocol):
    def list_reviews(self, *, status: str | None = "open") -> list[dict[str, Any]]: ...
    def get_review(self, review_id: str) -> dict[str, Any]: ...
    def list_agent_runs(self, *, limit: int = 100) -> list[dict[str, Any]]: ...
    def get_agent_run(self, run_id: str) -> dict[str, Any]: ...
