import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState, type FormEvent } from "react";
import { Link, useNavigate, useParams, useSearchParams } from "react-router-dom";

import { analyzeJob, createApplication, generateJobFitProposal, generateResumeDirections, getApplications, getJobFitProposals, getJobPost, getJobPosts, getOpportunity, getResumeDirections, importJobFile, importJobText, importJobUrl, resolveJobFitProposal, resolveResumeDirections, type JobAnalysisSummary, type JobFitProposal, type ResumeDirectionProposal } from "./api";
import { formatChinaTime } from "./time";

const RECOMMENDATIONS: Record<string, string> = { blocked: "硬条件不满足", high_priority: "高优先级", consider: "值得考虑", low_priority: "低优先级" };
const CATEGORIES: Record<string, string> = { skill: "技能", experience: "经验", education: "学历", language: "语言", location: "地点", work_mode: "工作方式", other: "其他" };

function MatchBadge({ analysis, requirementCount }: { analysis: JobAnalysisSummary | null; requirementCount: number }) {
  if (!requirementCount || !analysis) return <span className="health-pill">尚无法评估</span>;
  return <span className={`health-pill ${analysis.hard_gate_passed ? "ok" : "blocked"}`}>{RECOMMENDATIONS[analysis.recommendation] ?? analysis.recommendation} · {analysis.score}</span>;
}

export function JobPoolPage() {
  const client = useQueryClient(); const navigate = useNavigate(); const query = useQuery({ queryKey: ["job-posts"], queryFn: getJobPosts });
  const [searchParams] = useSearchParams(); const opportunityId = searchParams.get("opportunityId") ?? undefined;
  const mailAnalysisId = searchParams.get("mailAnalysisId") ?? undefined;
  const mailCompany = searchParams.get("company") ?? ""; const mailJobTitle = searchParams.get("jobTitle") ?? "";
  const opportunity = useQuery({ queryKey: ["opportunity", opportunityId], queryFn: () => getOpportunity(opportunityId ?? ""), enabled: Boolean(opportunityId) });
  const [result, setResult] = useState<string | null>(null);
  const done = async (job: { id: string; duplicate: boolean; version: number }) => { setResult(job.duplicate ? "相同岗位内容已存在，没有重复保存。" : "岗位已保存，并完成可信事实匹配。"); await client.invalidateQueries({ queryKey: ["job-posts"] }); if (mailAnalysisId) navigate(`/job-posts/${job.id}`); };
  const paste = useMutation({ mutationFn: ({ name, text }: { name: string; text: string }) => importJobText(name, text, opportunityId, mailAnalysisId), onSuccess: done });
  const upload = useMutation({ mutationFn: (file: File) => importJobFile(file, opportunityId, mailAnalysisId), onSuccess: done }); const fetchUrl = useMutation({ mutationFn: (url: string) => importJobUrl(url, opportunityId, mailAnalysisId), onSuccess: done });
  function submitText(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); paste.mutate({ name: String(data.get("name")), text: String(data.get("text")) }); }
  function submitUrl(event: FormEvent<HTMLFormElement>) { event.preventDefault(); fetchUrl.mutate(String(new FormData(event.currentTarget).get("url"))); }
  const error = paste.error ?? upload.error ?? fetchUrl.error;
  return <><header className="page-header"><div><p className="eyebrow">具体岗位</p><h1>目标岗位</h1><p>保存完整 JD、分析匹配依据，并从这里进入材料准备和申请跟踪。</p></div><span className="health-pill ok">{query.data?.total ?? 0} 个岗位</span></header>
    {opportunity.data && <section className="notice opportunity-note"><strong>正在为招聘机会导入具体 JD</strong><p>{opportunity.data.company} · {opportunity.data.batch}。导入完成后会保留机会与岗位的可追溯关联。</p></section>}
    {mailAnalysisId && <section className="notice opportunity-note"><strong>正在从招聘邮件建立投递档案</strong><p>{mailCompany || "公司待确认"} · {mailJobTitle || "岗位待确认"}。请导入真实完整 JD，随后在岗位详情确认加入申请跟踪；邮件证据会自动关联到新申请。</p></section>}
    <section className="import-grid job-import-grid"><form className="panel" onSubmit={submitText}><p className="eyebrow">粘贴岗位</p><h2>粘贴岗位正文</h2><input name="name" defaultValue={mailAnalysisId ? `${mailCompany || "招聘邮件"} · ${mailJobTitle || "岗位"}` : ""} placeholder="来源名称，例如：公司官网" required /><textarea name="text" rows={10} placeholder="建议保留职位、公司、地点、截止时间和任职要求" required /><button disabled={paste.isPending}>导入并分析</button></form>
      <div className="job-import-stack"><form className="panel upload-card"><p className="eyebrow">文件导入</p><h2>上传岗位文件</h2><p>支持 TXT、Markdown 和带文本层的 PDF。</p><label className="file-picker"><input type="file" aria-label="选择岗位文件并导入" accept=".txt,.md,.markdown,.pdf" onChange={(event) => { const file = event.target.files?.[0]; if (file) upload.mutate(file); }} /><span>{upload.isPending ? "正在解析岗位文件…" : "选择岗位文件并导入"}</span></label></form>
      <form className="panel" onSubmit={submitUrl}><p className="eyebrow">公开网页</p><h2>从公开 URL 获取</h2><p>点击后才会访问该公开网页；本地/内网地址和重定向会被拒绝。</p><input name="url" type="url" placeholder="https://example.com/jobs/123" required /><button className="secondary" disabled={fetchUrl.isPending}>确认访问并导入</button></form></div></section>
    {result && <section className="notice success">{result}</section>}{error && <section className="notice error">{error.message}</section>}
    {!query.isLoading && !query.data?.total && <section className="empty-state"><div className="empty-icon">＋</div><h2>岗位池还是空的</h2><p>先粘贴一个真实 JD。系统会保存原文和版本，并只用已确认职业事实生成匹配证据。</p></section>}
    <section className="job-list">{query.data?.items.map((job) => <Link className="panel job-card" to={`/job-posts/${job.id}`} key={job.id}><div><span className="category-tag">{job.company}</span><h2>{job.title}</h2><p>{job.location ?? "地点待确认"} · {job.work_mode ?? job.employment_type ?? "类型待确认"}</p></div><MatchBadge analysis={job.latest_analysis} requirementCount={job.requirement_count} /></Link>)}</section></>;
}

export function JobDetailPage() {
  const { id = "" } = useParams(); const client = useQueryClient(); const navigate = useNavigate();
  const [directionChoices, setDirectionChoices] = useState<Record<string, string[]>>({});
  const query = useQuery({ queryKey: ["job-post", id], queryFn: () => getJobPost(id), enabled: Boolean(id) });
  const applications = useQuery({ queryKey: ["applications"], queryFn: getApplications, enabled: Boolean(id) });
  const agentFits = useQuery({ queryKey: ["job-fit-proposals", id], queryFn: () => getJobFitProposals(id), enabled: Boolean(id) });
  const directions = useQuery({ queryKey: ["resume-directions", id], queryFn: () => getResumeDirections(id), enabled: Boolean(id) });
  const rerun = useMutation({ mutationFn: () => analyzeJob(id), onSuccess: async () => { await client.invalidateQueries({ queryKey: ["job-post", id] }); await client.invalidateQueries({ queryKey: ["job-posts"] }); } });
  const generateAgentFit = useMutation({ mutationFn: () => generateJobFitProposal(id), onSuccess: async () => { await client.invalidateQueries({ queryKey: ["job-fit-proposals", id] }); await client.invalidateQueries({ queryKey: ["unified-reviews"] }); } });
  const resolveAgentFit = useMutation({ mutationFn: ({ proposal, resolution }: { proposal: JobFitProposal; resolution: "confirmed" | "rejected" }) => resolveJobFitProposal(proposal, resolution), onSuccess: async () => { await client.invalidateQueries({ queryKey: ["job-fit-proposals", id] }); await client.invalidateQueries({ queryKey: ["job-post", id] }); await client.invalidateQueries({ queryKey: ["job-posts"] }); await client.invalidateQueries({ queryKey: ["unified-reviews"] }); } });
  const generateDirections = useMutation({ mutationFn: () => generateResumeDirections(id), onSuccess: async () => { await client.invalidateQueries({ queryKey: ["resume-directions", id] }); await client.invalidateQueries({ queryKey: ["unified-reviews"] }); } });
  const resolveDirections = useMutation({ mutationFn: ({ proposal, resolution }: { proposal: ResumeDirectionProposal; resolution: "confirmed" | "rejected" }) => resolveResumeDirections(proposal, resolution, directionChoices[proposal.id] ?? []), onSuccess: async () => { await client.invalidateQueries({ queryKey: ["resume-directions", id] }); await client.invalidateQueries({ queryKey: ["unified-reviews"] }); } });
  const track = useMutation({ mutationFn: () => createApplication(id), onSuccess: async (application) => {
    await client.invalidateQueries({ queryKey: ["applications"] });
    navigate(`/applications/${application.id}`);
  } });
  if (query.isLoading) return <section className="empty-state"><p>正在读取岗位…</p></section>;
  if (query.error || !query.data) return <section className="notice error">{query.error?.message ?? "岗位不存在"}</section>;
  const job = query.data; const analysis = job.analyses[0];
  const analysisReady = job.requirements.length > 0 && Boolean(analysis);
  const analysisBusy = rerun.isPending || generateAgentFit.isPending;
  const existingApplication = applications.data?.items?.find(item =>
    item.job_post_id === job.id && !item.archived_at,
  );
  const actions = analysisReady
    ? <><Link className="download-button" to={`/materials?jobId=${job.id}`}>准备申请材料</Link>{existingApplication
      ? <Link className="download-button" to={`/applications/${existingApplication.id}`}>查看申请</Link>
      : <button onClick={() => track.mutate()} disabled={track.isPending || applications.isLoading}>{track.isPending ? "正在创建…" : "开始跟踪申请"}</button>}</>
    : <button onClick={() => rerun.mutate()} disabled={analysisBusy}>{analysisBusy ? "正在分析…" : "重新分析岗位"}</button>;
  return <><header className="page-header job-detail-header"><div><p className="eyebrow"><Link to="/job-posts">目标岗位</Link> / {job.company}</p><h1>{job.title}</h1><p>{job.location ?? "地点待确认"} · {job.work_mode ?? job.employment_type ?? "类型待确认"}{job.deadline_at ? ` · 截止 ${formatChinaTime(job.deadline_at)}（北京时间）` : ""}</p></div><div className="header-actions primary-actions">{actions}<details className="secondary-actions"><summary>更多岗位操作</summary><div><button className="secondary" onClick={() => generateDirections.mutate()} disabled={!analysisReady || generateDirections.isPending}>规划简历方向</button><button className="secondary" onClick={() => generateAgentFit.mutate()} disabled={!job.requirements.length || generateAgentFit.isPending}>深入分析岗位</button>{analysisReady && <button className="secondary" onClick={() => rerun.mutate()} disabled={rerun.isPending}>更新匹配结果</button>}<small>系统会根据岗位要求和已确认经历选择合适的分析方式。</small></div></details></div></header>
    {track.error && <section className="notice error">{track.error.message}</section>}
    {!analysisReady && <section className="notice warning"><strong>尚无法判断岗位是否适合</strong><p>{job.requirements.length === 0 ? "当前岗位正文没有提取出有效任职要求。请检查原文是否完整，然后重新分析；在此之前不能生成材料或创建申请。" : "当前岗位还没有有效分析结果，请先重新分析。"}</p></section>}
    <section className="metric-grid"><article><span>岗位匹配</span><strong>{analysisReady ? analysis?.score : "—"}</strong><small>{analysisReady ? "用于比较投入优先级" : "等待有效岗位要求"}</small></article><article><span>硬性条件</span><strong>{!analysisReady ? "尚无法判断" : analysis?.hard_gate_passed ? "通过" : "未通过"}</strong><small>{analysisReady ? `${analysis?.must_gap_count ?? 0} 个硬条件缺口` : "分析完成后显示"}</small></article><article><span>经历依据</span><strong>{analysisReady ? analysis?.matched_count : "—"}</strong><small>{analysisReady ? "项要求有可信事实" : "等待分析"}</small></article><article><span>信息完整度</span><strong>{job.requirements.length}</strong><small>项任职要求已识别</small></article></section>
    {analysisReady && !analysis?.hard_gate_passed && <section className="notice error"><strong>该岗位存在未满足的硬性条件</strong><p>总分不会覆盖硬门槛。请检查下方缺口，确认事实库是否缺失或确实不符合。</p></section>}
    <section className="panel"><div className="panel-heading"><div><p className="eyebrow">匹配建议</p><h2>岗位投入判断</h2></div><span>{agentFits.data?.total ?? 0} 份建议</span></div>{agentFits.data?.items.map(proposal => <article className="mail-intelligence-item" key={proposal.id}><strong>{proposal.content.summary}</strong><p>{proposal.content.recommendationContext}</p><p>要求匹配 {proposal.decision_projection.requirement_score} · 偏好调整 {proposal.decision_projection.preference_adjustment >= 0 ? "+" : ""}{proposal.decision_projection.preference_adjustment} · 准备成本 {proposal.decision_projection.cost_adjustment} · 综合判断 {proposal.decision_projection.decision_score}（{RECOMMENDATIONS[proposal.decision_projection.priority] ?? proposal.decision_projection.priority}）</p><small>{proposal.decision_projection.reasons.join("；") || "未设置影响该岗位的显式偏好"} · 材料修改量 {proposal.content.materialEffort} · 预计准备 {proposal.content.preparationHours} 小时</small><details className="audit-details"><summary>查看智能功能记录</summary><Link to="/agent-runs">{proposal.agent_run_id}</Link></details><div className="detail-grid"><div><h3>优势</h3><ul>{proposal.content.strengths.map(item => <li key={item}>{item}</li>)}</ul></div><div><h3>风险</h3><ul>{proposal.content.risks.map(item => <li key={item}>{item}</li>)}</ul></div></div><details><summary>逐项匹配依据（{proposal.content.assessments.length}）</summary>{proposal.content.assessments.map(item => <p className="history-row" key={item.requirementId}>{item.decision === "matched" ? "匹配" : "缺口"} · {item.interpretation}<small>{item.rationale} · 事实依据 {item.evidenceFactIds.join("、") || "无直接证据"}{item.transferableFactIds.length ? ` · 可迁移 ${item.transferableFactIds.join("、")}` : ""}</small></p>)}</details>{proposal.status === "proposed" ? <div className="fact-actions"><button onClick={() => resolveAgentFit.mutate({ proposal, resolution: "confirmed" })}>确认匹配建议</button><button className="secondary" onClick={() => resolveAgentFit.mutate({ proposal, resolution: "rejected" })}>拒绝</button></div> : <span className={`health-pill ${proposal.status === "confirmed" ? "ok" : "blocked"}`}>{proposal.status === "confirmed" ? "已确认" : "已拒绝"}</span>}</article>)}{!agentFits.data?.total && <p>还没有深入匹配建议。点击“深入分析岗位”后，结果会先等待你确认，不会直接改变正式判断。</p>}</section>
    <section className="panel"><div className="panel-heading"><div><p className="eyebrow">简历方向规划</p><h2>比较简历修改方向</h2></div><span>{directions.data?.selections.filter(item => item.status === "active").length ? "已确认方向" : `${directions.data?.proposals.length ?? 0} 组建议`}</span></div>{directions.data?.selections.filter(item => item.status === "active").map(selection => <section className="notice success" key={selection.id}><strong>当前方向：{selection.selected_directions.map(item => item.name).join(" + ")}</strong><p>该方向会作为下一步材料撰写依据，历史记录仍会保留。</p></section>)}{directions.data?.proposals.map(proposal => <article className="mail-intelligence-item" key={proposal.id}><p>{proposal.content.comparisonNote}</p><details className="audit-details"><summary>查看智能功能记录</summary><Link to="/agent-runs">{proposal.agent_run_id}</Link></details><div className="detail-grid">{proposal.content.directions.map(direction => { const selected = directionChoices[proposal.id]?.includes(direction.directionId) ?? false; return <article className={`panel ${selected ? "selected" : ""}`} key={direction.directionId}><label><input type="checkbox" checked={selected} disabled={proposal.status !== "proposed"} onChange={() => setDirectionChoices(previous => { const current = previous[proposal.id] ?? []; const next = current.includes(direction.directionId) ? current.filter(item => item !== direction.directionId) : current.length < 2 ? [...current, direction.directionId] : current; return { ...previous, [proposal.id]: next }; })} /> 选择方向</label><h3>{direction.name}</h3><p>{direction.narrative}</p><small>预计修改 {direction.estimatedChangePercent}% · {direction.expectedPages} 页 · 强调事实 {direction.emphasizeFactIds.join("、")}</small><p>{direction.rationale}</p>{direction.gaps.map(item => <p className="form-error" key={item}>缺口：{item}</p>)}{direction.risks.map(item => <p key={item}>风险：{item}</p>)}</article>})}</div>{proposal.status === "proposed" ? <div className="fact-actions"><button disabled={!directionChoices[proposal.id]?.length} onClick={() => resolveDirections.mutate({ proposal, resolution: "confirmed" })}>确认所选方向</button><button className="secondary" onClick={() => resolveDirections.mutate({ proposal, resolution: "rejected" })}>拒绝本组</button></div> : <span className={`health-pill ${proposal.status === "confirmed" ? "ok" : "blocked"}`}>{proposal.status === "confirmed" ? "已完成选择" : "已拒绝"}</span>}</article>)}{!directions.data?.proposals.length && <p>先生成 2–4 个方向，再选择一个或组合两个；系统不会直接替你决定唯一简历。</p>}</section>
    <section className="panel evidence-panel"><div className="panel-heading"><div><p className="eyebrow">岗位要求与证据</p><h2>要求与可信证据</h2></div><span>{job.requirements.length} 项</span></div>{analysis?.evidence.map((item) => <article className={`evidence-row ${item.decision}`} key={item.requirement.id}><div className="requirement-copy"><div><span className={`requirement-level ${item.requirement.level}`}>{item.requirement.level === "must" ? "硬性" : "优先"}</span><span>{CATEGORIES[item.requirement.category] ?? item.requirement.category}</span></div><h3>{item.requirement.description}</h3><blockquote>{item.requirement.evidence_text}</blockquote></div><div className="evidence-copy"><strong>{item.decision === "matched" ? "有证据" : "缺口"}</strong><p>{item.rationale}</p>{item.facts.map((fact) => <div className="fact-proof" key={fact.id}>{fact.value}<small>{CATEGORIES[fact.category] ?? fact.category} · {fact.field_key}</small></div>)}</div></article>)}{!job.requirements.length && <div className="empty-state compact"><h3>没有识别到任职要求</h3><p>检查岗位原文是否包含“任职要求”“岗位要求”等完整段落，再点击“重新分析岗位”。</p></div>}</section>
    <section className="detail-grid"><details className="panel"><summary>查看岗位原文</summary><pre className="raw-text">{job.raw_text}</pre></details><details className="panel audit-details"><summary>查看版本与分析记录</summary><div className="panel-heading"><h2>版本与分析记录</h2><span>{job.analyses.length} 次分析</span></div>{job.versions.map((version) => <p className="history-row" key={version.id}>岗位版本 {version.version_number}<small>{formatChinaTime(version.created_at)}（北京时间） · 校验值 {version.content_hash.slice(0, 12)}</small></p>)}{job.analyses.map((item) => <p className="history-row" key={item.id}>分析：{RECOMMENDATIONS[item.recommendation]} · {item.score}<small>{formatChinaTime(item.created_at)}（北京时间）</small></p>)}</details></section>{(agentFits.error || generateAgentFit.error || resolveAgentFit.error || directions.error || generateDirections.error || resolveDirections.error) && <section className="notice error">{agentFits.error?.message ?? generateAgentFit.error?.message ?? resolveAgentFit.error?.message ?? directions.error?.message ?? generateDirections.error?.message ?? resolveDirections.error?.message}</section>}</>;
}
