import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState, type FormEvent } from "react";
import { Link, useNavigate, useParams, useSearchParams } from "react-router-dom";

import { createApplication, editMaterial, finalizeMaterial, forkResumeFromMaterial, generateMaterial, generateMaterialAgentProposal, getApplications, getJobPosts, getMaterial, getMaterialAgentProposals, getMaterials, getResumeDirections, getResumeSeries, getResumeVersionDiff, resolveMaterialAgentProposal, reviewMaterial, type Material, type MaterialAgentProposal, type MaterialType } from "./api";
import { formatChinaTime } from "./time";

const TYPE_LABELS: Record<MaterialType, string> = { resume: "定制简历", cover_letter: "求职信", introduction: "自我介绍" };
const STATUS_LABELS: Record<string, string> = { draft: "需要修复", reviewed: "审查通过", final: "已确认 Final" };

export function MaterialsPage() {
  const [params] = useSearchParams(); const navigate = useNavigate(); const client = useQueryClient();
  const targetJobId = params.get("jobId") ?? "";
  const [resumeId, setResumeId] = useState("");
  const jobs = useQuery({ queryKey: ["job-posts"], queryFn: getJobPosts }); const materials = useQuery({ queryKey: ["materials"], queryFn: getMaterials });
  const resumes = useQuery({ queryKey: ["resume-series"], queryFn: getResumeSeries });
  const directions = useQuery({ queryKey: ["resume-directions", targetJobId], queryFn: () => getResumeDirections(targetJobId), enabled: Boolean(targetJobId) });
  const agentProposals = useQuery({ queryKey: ["material-agent-proposals", targetJobId], queryFn: () => getMaterialAgentProposals(targetJobId), enabled: Boolean(targetJobId) });
  const create = useMutation({ mutationFn: generateMaterial, onSuccess: async (item) => { await Promise.all([client.invalidateQueries({ queryKey: ["materials"] }), client.invalidateQueries({ queryKey: ["resume-series"] })]); navigate(`/materials/${item.id}`); } });
  const generateAgent = useMutation({ mutationFn: () => generateMaterialAgentProposal({ job_post_id: targetJobId, resume_name: "我的基础简历", ...(resumeId ? { resume_id: resumeId } : {}) }), onSuccess: () => client.invalidateQueries({ queryKey: ["material-agent-proposals", targetJobId] }) });
  const resolveAgent = useMutation({ mutationFn: ({ proposal, resolution }: { proposal: MaterialAgentProposal; resolution: "confirmed" | "rejected" }) => resolveMaterialAgentProposal(proposal, resolution), onSuccess: async (proposal) => { await Promise.all([client.invalidateQueries({ queryKey: ["material-agent-proposals", targetJobId] }), client.invalidateQueries({ queryKey: ["materials"] }), client.invalidateQueries({ queryKey: ["resume-series"] })]); if (proposal.material_draft_id) navigate(`/materials/${proposal.material_draft_id}`); } });
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); create.mutate({ job_post_id: String(data.get("job_post_id")), material_type: String(data.get("material_type")) as MaterialType, name: String(data.get("name") ?? ""), ...(resumeId ? { resume_id: resumeId } : {}) }); }
  return <><header className="page-header"><div><p className="eyebrow">事实绑定材料</p><h1>申请材料</h1></div><span className="health-pill ok">{materials.data?.total ?? 0} 份</span></header>
    {directions.data?.selections.find(item => item.status === "active") && <section className="notice success"><strong>已确认简历方向</strong><p>{directions.data.selections.find(item => item.status === "active")?.selected_directions.map(item => item.name).join(" + ")}。材料撰写 Agent 会锁定并使用这个选择；下方本地生成器仍作为确定性基线保留。</p></section>}
    {targetJobId && <section className="panel"><div className="panel-heading"><div><p className="eyebrow">Agent 撰写与独立复核</p><h2>生成可审核的定制简历候选</h2><p>每个内容块必须引用已确认事实；确认前不会写入正式材料版本。</p></div><button onClick={() => generateAgent.mutate()} disabled={generateAgent.isPending || !directions.data?.selections.some(item => item.status === "active")}>{generateAgent.isPending ? "正在撰写并复核…" : "生成 Agent 材料候选"}</button></div>{generateAgent.error && <p className="form-error">{generateAgent.error.message}</p>}{agentProposals.data?.items.map(proposal => <article className="material-block" key={proposal.id}><div className="panel-heading"><div><h3>{proposal.content.title}</h3><p>{proposal.content.rationale}</p></div><span className={`health-pill ${proposal.review.verdict === "pass" ? "ok" : "blocked"}`}>{proposal.review.verdict === "pass" ? "复核通过" : "需要修订"}</span></div>{proposal.content.blocks.map(block => <div className="finding info" key={block.blockId}><strong>{block.section}</strong><p>{block.text}</p><details><summary>查看引用依据</summary><small>事实：{block.factIds.join(", ")} · 岗位要求：{block.requirementIds.join(", ") || "无"}</small></details></div>)}<h4>复核结论</h4><p>{proposal.review.summary}</p>{proposal.review.findings.map((finding, index) => <div className={`finding ${finding.severity}`} key={`${finding.code}-${index}`}><strong>{finding.severity} · {finding.code}</strong><p>{finding.message}</p></div>)}{proposal.status === "proposed" && <div className="button-row"><button className="secondary" onClick={() => resolveAgent.mutate({ proposal, resolution: "rejected" })}>拒绝</button><button onClick={() => resolveAgent.mutate({ proposal, resolution: "confirmed" })} disabled={proposal.review.verdict !== "pass" || resolveAgent.isPending}>确认并生成正式版本</button></div>}</article>)}</section>}
    <section className="panel material-create"><div><p className="eyebrow">本地确定性生成</p><h2>为真实岗位生成材料</h2><p>本地基线只重排已确认事实；可从基础或方向简历派生岗位定制版本。</p></div><form className="form-grid" onSubmit={submit}><label>岗位<select name="job_post_id" defaultValue={params.get("jobId") ?? ""} required><option value="" disabled>选择岗位</option>{jobs.data?.items.map((job) => <option value={job.id} key={job.id}>{job.company} · {job.title}</option>)}</select></label><label>材料类型<select name="material_type" defaultValue="resume"><option value="resume">定制简历</option><option value="cover_letter">求职信</option><option value="introduction">自我介绍</option></select></label><label>来源简历系列<select name="resume_id" value={resumeId} onChange={(event) => setResumeId(event.target.value)}><option value="">新建基础系列</option>{resumes.data?.items.map((resume) => <option value={resume.id} key={resume.id}>[{resume.series_type === "base" ? "基础" : "方向"}] {resume.name}（{resume.material_count} 份材料）</option>)}</select></label><label>新系列名称<input name="name" defaultValue="我的基础简历" required={!resumeId} disabled={Boolean(resumeId)} /></label><button disabled={create.isPending || !jobs.data?.total}>{create.isPending ? "生成与审查中…" : "生成事实绑定草稿"}</button>{create.error && <p className="form-error">{create.error.message}</p>}</form></section>
    <section className="panel"><div className="panel-heading"><div><p className="eyebrow">简历版本关系</p><h2>可复用简历系列</h2></div><span>{resumes.data?.total ?? 0} 个</span></div>{resumes.data?.items.map(resume => <div className="history-row" key={resume.id}><strong>{resume.series_type === "base" ? "基础" : "方向"} · {resume.name}</strong><small>{resume.direction_label ? `${resume.direction_label} · ` : ""}{resume.latest_version ? `v${resume.latest_version.version_number} · ${resume.latest_version.content_hash.slice(0, 10)}` : "尚无版本"}</small></div>)}</section>
    {!materials.data?.total && <section className="empty-state"><div className="empty-icon">✦</div><h2>还没有申请材料</h2><p>先在岗位池导入并分析一个岗位，再从这里生成定制简历。</p></section>}
    <section className="job-list material-list">{materials.data?.items.map((item) => <Link className="panel job-card" to={`/materials/${item.id}`} key={item.id}><div><span className="category-tag">{TYPE_LABELS[item.material_type]}</span><h2>{item.job_title}</h2><p>{item.company} · 内容 v{item.current_version_number} · 工作流 v{item.version}</p>{item.strategy_stale && <small className="form-error">基础档案已变化，需要复核材料策略</small>}</div><span className={`health-pill ${!item.strategy_stale && (item.status === "final" || item.status === "reviewed") ? "ok" : "blocked"}`}>{item.strategy_stale ? "策略已失效" : STATUS_LABELS[item.status]}</span></Link>)}</section></>;
}

export function MaterialDetailPage() {
  const { id = "" } = useParams(); const client = useQueryClient(); const navigate = useNavigate();
  const query = useQuery({ queryKey: ["material", id], queryFn: () => getMaterial(id), enabled: Boolean(id) });
  const applications = useQuery({ queryKey: ["applications"], queryFn: getApplications });
  const refresh = async () => { await client.invalidateQueries({ queryKey: ["material", id] }); await client.invalidateQueries({ queryKey: ["materials"] }); };
  const review = useMutation({ mutationFn: () => reviewMaterial(id), onSuccess: refresh });
  const finalize = useMutation({ mutationFn: (material: Material) => finalizeMaterial(material), onSuccess: refresh });
  const createTracking = useMutation({
    mutationFn: (jobPostId: string) => createApplication(jobPostId),
    onSuccess: async application => {
      await client.invalidateQueries({ queryKey: ["applications"] });
      navigate(`/applications/${application.id}`);
    },
  });
  const resumes = useQuery({ queryKey: ["resume-series"], queryFn: getResumeSeries });
  if (query.isLoading) return <section className="empty-state"><p>正在读取材料版本…</p></section>;
  if (query.error || !query.data) return <section className="notice error">{query.error?.message ?? "材料不存在"}</section>;
  const material = query.data;
  const existingApplication = applications.data?.items?.find(item => item.job_post_id === material.job_post_id);
  const comparisonFrom = material.source_resume_version_id ?? material.versions.at(-1)?.id ?? null;
  return <><header className="page-header job-detail-header"><div><p className="eyebrow"><Link to="/materials">申请材料</Link> / {material.company}</p><h1>{material.current_version.title}</h1><p>{TYPE_LABELS[material.material_type]} · 内容 v{material.current_version.version_number}</p></div><span className={`health-pill ${material.status === "draft" ? "blocked" : "ok"}`}>{STATUS_LABELS[material.status]}</span></header>
    {material.strategy_stale && <section className="notice error"><strong>材料策略需要重新确认</strong><p>{material.strategy_stale_reason} 历史版本和 Final 快照不会被自动改写；保存新版本后清除此标记。</p></section>}
    <section className="notice success"><strong>版本血缘</strong><p>{material.resume_series_type === "direction" ? "方向简历" : "基础简历"} → 岗位定制 v{material.current_version.version_number}{material.source_resume_version_id ? "，来源版本已锁定。" : "，当前版本没有上游可复用版本。"}</p>{comparisonFrom && comparisonFrom !== material.current_version.id && <Link to={`/resume-diff/${comparisonFrom}/${material.current_version.id}`}>查看来源/初始版本与当前版本差异</Link>}</section>
    <section className="metric-grid"><article><span>内容版本</span><strong>v{material.current_version.version_number}</strong><small>父版本 {material.current_version.parent_version_id ? "已记录" : "初始草稿"}</small></article><article><span>材料复核</span><strong>{material.review?.error_count ?? 0} 错误</strong><small>{material.review?.warning_count ?? 0} 条风险提示</small></article><article><span>事实集合</span><strong>{material.current_version.fact_set_hash.slice(0, 10)}</strong><small>生成时锁定</small></article><article><span>导出</span><strong>{material.export ? `${material.export.page_count} 页` : "未生成"}</strong><small>{material.export?.text_layer_ok ? "ATS 文本层通过" : "最终确认后生成"}</small></article></section>
    {material.review?.findings.length ? <section className="panel findings"><div className="panel-heading"><h2>复核发现</h2><span>{material.review.findings.length} 项</span></div>{material.review.findings.map((item) => <div className={`finding ${item.severity}`} key={item.id}><strong>{item.severity === "error" ? "阻断" : "风险"} · {item.code}</strong><p>{item.message}</p></div>)}</section> : <section className="notice success">复核未发现阻断问题。所有材料表达均有事实快照支持。</section>}
    <MaterialEditor material={material} onSaved={refresh} />
    {material.material_type === "resume" && material.status !== "draft" && <ResumeForkPanel material={material} resumes={resumes.data?.items ?? []} />}
    {material.status !== "final" && <section className="panel final-actions"><div><h2>Final 门禁</h2><p>确认后版本不可编辑，并生成经过文本层和真实渲染验证的 PDF。</p></div><div><button className="secondary" onClick={() => review.mutate()} disabled={review.isPending}>重新审查</button><button onClick={() => finalize.mutate(material)} disabled={finalize.isPending || Boolean(material.review?.error_count)}>确认 Final 并导出 PDF</button></div>{(review.error || finalize.error) && <p className="form-error">{review.error?.message ?? finalize.error?.message}</p>}</section>}
    {material.status === "final" && <section className="panel next-action-card"><div><p className="eyebrow">下一步</p><h2>建立申请进度</h2><p>材料已经确认，可以开始跟踪投递、测评、面试和结果。</p></div>{existingApplication ? <Link className="download-button" to={`/applications/${existingApplication.id}`}>查看已有申请进度</Link> : <button type="button" onClick={() => createTracking.mutate(material.job_post_id)} disabled={createTracking.isPending}>{createTracking.isPending ? "正在创建…" : "创建申请"}</button>}{createTracking.error && <p className="form-error">{createTracking.error.message}</p>}</section>}
    {material.export && <section className="panel export-result"><div><p className="eyebrow">已验证 PDF</p><h2>最终导出已通过</h2><p>{(material.export.size_bytes / 1024).toFixed(1)} KB · {material.export.page_count} 页 · 文本层 {material.export.text_layer_ok ? "通过" : "失败"} · 渲染 {material.export.render_ok ? "通过" : "失败"}</p><details><summary>查看文件校验值</summary><code>{material.export.sha256}</code></details><p><a className="download-button" href={material.export.download_url}>下载 PDF</a></p></div><img src={material.export.preview_url} alt="最终 PDF 第一页渲染预览" /></section>}
    <section className="panel"><div className="panel-heading"><h2>不可变版本链</h2><span>{material.versions.length} 个版本</span></div>{material.versions.map((version) => <p className="history-row" key={version.id}>v{version.version_number} · {STATUS_LABELS[version.status] ?? version.status}<small>{formatChinaTime(version.created_at)}（北京时间） · {version.content_hash.slice(0, 12)}</small></p>)}</section></>;
}

function ResumeForkPanel({ material, resumes }: { material: Material; resumes: Awaited<ReturnType<typeof getResumeSeries>>["items"] }) {
  const client = useQueryClient(); const [seriesType, setSeriesType] = useState<"base" | "direction">("base");
  const fork = useMutation({ mutationFn: (body: { name: string; parent_resume_id?: string; direction_label?: string }) => forkResumeFromMaterial({ material_id: material.id, series_type: seriesType, ...body }), onSuccess: () => client.invalidateQueries({ queryKey: ["resume-series"] }) });
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); fork.mutate({ name: String(data.get("name")), ...(seriesType === "direction" ? { parent_resume_id: String(data.get("parent_resume_id")), direction_label: String(data.get("direction_label")) } : {}) }); }
  return <section className="panel"><div><p className="eyebrow">复用当前版本</p><h2>保存为可复用简历版本</h2><p>复制当前不可变内容和事实快照；方向简历必须从基础简历派生。</p></div><form className="form-grid" onSubmit={submit}><label>系列类型<select value={seriesType} onChange={event => setSeriesType(event.target.value as "base" | "direction")}><option value="base">基础简历</option><option value="direction">方向简历</option></select></label><label>名称<input name="name" required defaultValue={seriesType === "base" ? "通用基础简历" : `${material.job_title}方向简历`} /></label>{seriesType === "direction" && <><label>父基础简历<select name="parent_resume_id" required defaultValue=""><option value="" disabled>选择基础简历</option>{resumes.filter(item => item.series_type === "base" && item.latest_version).map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>方向名称<input name="direction_label" required placeholder="例如：后端工程" /></label></>}<button disabled={fork.isPending}>{fork.isPending ? "保存中…" : "保存可复用版本"}</button>{fork.data && <p className="notice success">已创建{fork.data.series_type === "base" ? "基础" : "方向"}简历：{fork.data.name}</p>}{fork.error && <p className="form-error">{fork.error.message}</p>}</form></section>;
}

export function ResumeDiffPage() {
  const { fromVersionId = "", toVersionId = "" } = useParams();
  const query = useQuery({ queryKey: ["resume-version-diff", fromVersionId, toVersionId], queryFn: () => getResumeVersionDiff(fromVersionId, toVersionId), enabled: Boolean(fromVersionId && toVersionId) });
  if (query.isLoading) return <section className="empty-state"><p>正在计算版本差异…</p></section>;
  if (query.error || !query.data) return <section className="notice error">{query.error?.message ?? "无法读取版本差异"}</section>;
  const diff = query.data;
  return <><header className="page-header"><div><p className="eyebrow"><Link to="/materials">申请材料</Link> / 版本比较</p><h1>简历版本差异</h1></div><span className="health-pill ok">{diff.summary.changed + diff.summary.added + diff.summary.removed} 项变化</span></header><section className="metric-grid"><article><span>新增块</span><strong>{diff.summary.added}</strong></article><article><span>删除块</span><strong>{diff.summary.removed}</strong></article><article><span>修改块</span><strong>{diff.summary.changed}</strong></article><article><span>事实变化</span><strong>{diff.fact_changes.added_fact_ids.length + diff.fact_changes.removed_fact_ids.length}</strong></article></section><section className="panel"><div className="panel-heading"><div><h2>{diff.from_version.title}</h2><small>{diff.from_version.version_scope} → {diff.to_version.version_scope}</small></div><span>{diff.blocks.length} 个内容块</span></div>{diff.blocks.map(block => <article className={`material-block finding ${block.change === "unchanged" ? "info" : "warning"}`} key={block.block_id}><strong>{block.change.toUpperCase()} · {block.block_id}</strong><div className="metric-grid"><div><small>之前</small><p>{block.before?.text ?? "—"}</p><code>{block.before?.fact_ids.join(", ") || "无事实引用"}</code></div><div><small>之后</small><p>{block.after?.text ?? "—"}</p><code>{block.after?.fact_ids.join(", ") || "无事实引用"}</code></div></div></article>)}</section></>;
}

function MaterialEditor({ material, onSaved }: { material: Material; onSaved: () => Promise<void> }) {
  const [values, setValues] = useState(() => Object.fromEntries(material.current_version.blocks.map((block) => [block.id, block.text])));
  const edit = useMutation({ mutationFn: () => editMaterial(material, material.current_version.blocks.map((block) => ({ id: block.id, text: values[block.id] ?? block.text }))), onSuccess: onSaved });
  return <section className="panel material-editor"><div className="panel-heading"><div><p className="eyebrow">表达与事实快照</p><h2>{material.status === "final" ? "最终内容" : "编辑事实表达"}</h2></div><span>{material.current_version.blocks.length} 条</span></div>{material.current_version.blocks.map((block) => <article className="material-block" key={block.id}><label>{block.section}<textarea rows={3} value={values[block.id] ?? block.text} readOnly={material.status === "final"} onChange={(event) => setValues((previous) => ({ ...previous, [block.id]: event.target.value }))} /></label><details open><summary>事实引用（{block.fact_snapshots.length}）</summary>{block.fact_snapshots.map((fact) => <blockquote key={fact.id}>{fact.value}<small>{fact.category} · {fact.field_key} · 事实版本 {fact.fact_version}</small></blockquote>)}</details></article>)}{material.status !== "final" && <button onClick={() => edit.mutate()} disabled={edit.isPending}>{edit.isPending ? "保存并审查中…" : "保存为新版本并重新审查"}</button>}{edit.error && <p className="form-error">{edit.error.message}</p>}</section>;
}
