"""Connector persistence contract."""

from __future__ import annotations

from typing import Any, Protocol


class ConnectorGateway(Protocol):
    def get_or_create_boss(self) -> dict[str, Any]: ...
    def update_boss(self, **values: Any) -> dict[str, Any]: ...
    def list_runs(self, *, limit: int = 20) -> list[dict[str, Any]]: ...
    def start_run(self, *, trigger_type: str) -> dict[str, Any]: ...
    def finish_run(self, run_id: str, **counts: Any) -> dict[str, Any]: ...
    def fail_run(self, run_id: str, *, error_code: str) -> dict[str, Any]: ...
    def source_event(self, **values: Any) -> tuple[dict[str, Any], bool]: ...
    def complete_event(self, event_id: str, *, job_post_id: str) -> None: ...
    def quarantine_event(self, event_id: str, *, error_code: str) -> None: ...
    def list_quarantine(self, *, limit: int = 50) -> list[dict[str, Any]]: ...
    def due(self) -> bool: ...


class OpenCliRunner(Protocol):
    def version(self) -> str: ...
    def boss_status(self, *, profile: str) -> dict[str, Any]: ...
    def boss_login(self, *, profile: str, timeout: int = 300) -> dict[str, Any]: ...
    def boss_search(
        self, *, profile: str, query: str, city: str, limit: int
    ) -> list[dict[str, Any]]: ...
    def boss_detail(self, *, profile: str, security_id: str) -> dict[str, Any]: ...
