"""Task, reminder, dashboard, and scheduler persistence contract."""

from __future__ import annotations

from typing import Any, Protocol


class TaskGateway(Protocol):
    def create_task(self, **kwargs: Any) -> dict[str, Any]: ...
    def list_tasks(self) -> list[dict[str, Any]]: ...
    def update_task(self, task_id: str, **kwargs: Any) -> dict[str, Any]: ...
    def create_reminder(self, task_id: str, **kwargs: Any) -> dict[str, Any]: ...
    def run_due(self, **kwargs: Any) -> dict[str, int]: ...
    def dashboard(self, **kwargs: Any) -> dict[str, Any]: ...
    def list_notifications(self) -> list[dict[str, Any]]: ...
    def read_notification(self, notification_id: str) -> dict[str, Any]: ...
